//create user
POST  http://localhost:5000/users
Content-Type: application/json

{
    "name":"Dodit",
    "email":"admin@op.gg",
    "password":"123456",
    "confirmPassword":"123456",
    "role":"admin"
}

###
//get all users
GET http://localhost:5000/users

###
//get user by id
GET http://localhost:5000/users/

###
//update insert
PATCH   http://localhost:5000/users/
Content-Type: application/json

{
    {
    "name":"Nami Updated",
    "email":"nami@op.gg",
    "password":"",
    "confirmPassword":"",
    "role":"admin"
}
}

###
//delete user
DELETE http://localhost:5000/logout

###
//login
POST http://localhost:5000/login
Content-Type: application/json
{
    "email":"user@gmail.com",
    "password":"12345"
}
###
POST http://localhost:5000/products
Content-Type: application/json

{
    "name":"Products 1",
    "price":"600"
}
###
GET  http://localhost:5000/me

###
GET http://localhost:5000/products